### ISSUE TITLE
kintaiyi.py   line 328 

### ISSUE THREAD

**Issue by i-arun-samui** [kentang2017/kintaiyi#1]
Hi,

in kintaiyi.py 
line 328  
return sum(sf_order[: sf_order.index(ty)])

should be 
return sum(se_order[: se_order.index(ty)])

right ?

**Comment by kentang2017** [comment]
you are correct!
Amended and i will update it on pypi

**Comment by i-arun-samui** [comment]
Thanks for your prompt answer 

you corrected it as :
return sum(se_order[: sf_order.index(ty)])

shouldn't it be :
return sum(se_order[: se_order.index(ty)])

?

**Comment by kentang2017** [comment]
return sum(se_order[: se_order.index(ty)])

**Comment by i-arun-samui** [comment]
<img width="1323" alt="Capture d’écran 2021-11-30 à 08 57 23" src="https://user-images.githubusercontent.com/31113686/143971886-39cb5e85-b6cc-41fd-8574-155523cd1d6d.png">

**Comment by kentang2017** [comment]
fixed and thx for your reminder

**Comment by i-arun-samui** [comment]
谢谢啦
