### ISSUE TITLE
2021/11/3

### ISSUE THREAD

**Issue by i-arun-samui** [kentang2017/kintaiyi#2]
Hi,
year = 2021
month = 11
day = 3
hour = 13

return  -> home_cal, [15, []]

is it normal ?

**Comment by kentang2017** [comment]
kintaiyi.Taiyi(2021,11,3,13).pan()
{'干支': ('辛丑', '戊戌', '乙卯', '癸未'), '農曆': {'月': 9, '日': 29}, '紀元': '壬子元第六紀', '時局': '陰遁44局', '太 乙': 2, '文昌': '未', '太歲': '未', '合神': '午', '計神': '丑', '始擊': '坤', '定目': '坤', '主算': [39, ['三才足數', ' 純陽']], '客算': [38, ['三才足數', '下和']], '定算': [38, ['三才足數', '下和']], '九宮': {8: '客將定將', 3: '', 4: '客參定參', 9: '主將飛鳥', 2: '太乙五風大游小游', 7: '主參八風', 6: '', 1: '', 5: '三風'}, '十六宮': {'子': '', '丑': '飛符', '艮': '', '寅': '地乙', '卯': '臣基民基帝符', '辰': '', '巽': '', '巳': '直符', '午': '合神天乙', '未': '文昌太歲', '申': '四神', '坤': '定目', '酉': '君基', '戌': '', '乾': '', '亥': '', '始擊': '坤', None: '太尊五福'}}

**Comment by i-arun-samui** [comment]
thanks !

can you have a look at year: 2021, month: 11, day: 5, hour: 12)

which return  '主算': [25, []],

{'干支': ('辛丑', '戊戌', '丁巳', '丙午'), '農曆': {'月': 10, '日': 1}, '紀元': '壬子元第六紀', '時局': '陰遁67局', '太乙': 2, '文昌': '乾', '太歲': '午', '合神': '未', '計神': '寅', '始擊': '戌', '定目': '戌', '主算': [25, []], '客算': [26, ['三才足數', '純陰']], '定算': [26, ['三才足數', '純陰']], '九宮': {8: '客參定參五風', 3: '大游', 4: '', 9: '', 5: '主將主參', 2: '太乙八風', 7: '三風', 6: '客將定將', 1: '飛鳥小游'}, '十六宮': {'子': [], '丑': ['直符'], '艮': [], '寅': ['民基', '天乙'], '卯': ['太尊'], '辰': ['四神'], '巽': [], '巳': ['帝符'], '午': ['太歲'], '未': ['合神'], '申': [], '坤': [], '酉': ['飛符'], '戌': ['始擊', '定目', '君基', '臣基', '地乙'], '乾': ['文昌'], '亥': []}}

correct ?

**Comment by kentang2017** [comment]
yes

**Comment by i-arun-samui** [comment]
Thanks
