### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by Oliver-F1** [kentang2017/kintaiyi#4]
你好，感谢你写的程序，但是有个问题，就是你项目中的sxtwl版本兼容问题，目前sxwtl最新版本为2.0.6，例如你的计时太乙神数只能使用新版本，使用旧版本就会报module 'sxtwl' has no attribute 'fromSolar'。而周易筮法只能使用旧版本，例如1.1.0，一个运行环境无法满足成功运行两个程序，所以能否将代码改成兼容性一样的版本呢

**Comment by kentang2017** [comment]
我有空修正一下呀
